name: Build_with_ubuntu_packages

on:
  push:
    branches:
      - master
      - REL_UNDER_PG13_STABLE
  pull_request:
    branches:
      - master
      - REL_UNDER_PG13_STABLE
  schedule:
    - cron: "0 1 * * SUN"         # only master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - name: cat version
      shell: bash -xe {0}
      run: |
         cat /etc/os-release
         uname -a

    - name: get current branch name
      shell: bash -xe {0}
      run: |
        if [ ${{ github.event_name }} = "pull_request" ]; then
          echo "BRANCH=${{ github.base_ref }}" >>  $GITHUB_ENV
        else # push
          echo "BRANCH=${GITHUB_REF##*/}" >>  $GITHUB_ENV
        fi

    - name: set build postgresql version
      shell: bash -xe {0}
      run: |
        declare -A versions=(
          ["master"]="13"
          ["REL_UNDER_PG13_STABLE"]="12"
        )
        [ -z "${versions[${{ env.BRANCH }}]}" ] && exit 1         # check if the key exists
        echo "PGVERSION=${versions[${{ env.BRANCH }}]}" >> $GITHUB_ENV

    - name: download packages for building
      shell: bash -xe {0}
      run: |
        # https://www.postgresql.org/download/linux/ubuntu/
        sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        sudo apt-get update
        sudo apt-get -y install           \
          build-essential                 \
          libpam-dev                      \
          libkrb5-dev                     \
          postgresql-${{ env.PGVERSION }} \
          postgresql-server-dev-${{ env.PGVERSION }}
        pg_config

    - uses: actions/checkout@v2

    - name: make  # only check if build is success. The tests are skipped because another workflow does so.
      shell: bash -xe {0}
      run: make

    - name: check version
      shell: bash -xe {0}
      run: bin/pg_bulkload --version
